server:
  port: 42550

logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR
      
keycloak:
  realm: mboss-realm-dev
  auth-server-url: http://35.198.54.93:8090/auth
  ssl-required: external
  resource: mboss-client-dev
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: 4c33b9d8-4972-4793-b53f-2f30c8af3025

spring:
  application:
    name: core-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://35.198.54.93:5432/dbcore
    username: develop
    password: 3162514
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: dbcore
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

eureka:
  instance:
    hostname: 35.198.54.93
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${GIT_USER}:${GIT_PASS}@${eureka.instance.hostname}:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    health:
      show-details: always