server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    basic:
      enabled: true
    user: 
      name: ${config.user}
      password: ${config.pass}

logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/