server:
  port: 8761

spring:
  application:
    name: discovery-service

  security:
    basic:
      enabled: true
    user:
      name: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}

logging:
  level:
    org:
      springframework:
        web:
          client: DEBUG
    com:
      netflix:
        discovery: DEBUG

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery-service:${server.port}/eureka/
