server:
  port: 8765

logging:
    level:
      root: INFO
      org:
        springframework:
          web: ERROR
        hibernate: ERROR

spring:
  application:
    name: gateway-service
    
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://10.0.0.108:8090/auth/realms/spring-cloud-gateway-realm/protocol/openid-connect/token
            issuer-uri: http://10.0.0.108:8090/auth/realms/spring-cloud-gateway-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring-cloud-gateway-client
            client-secret: 0c592926-0ebc-418f-8f60-85e7f70d7260
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
      default-filters:
      - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    register-with-eureka: true
    fetch-registry: true