server:
  port: 8765

logging:
    level:
      root: INFO
      org:
        springframework:
          web: ERROR
        hibernate: ERROR

spring:
  application:
    name: gateway-service
    
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:8080/auth/realms/mboss-realm/protocol/openid-connect/token
            issuer-uri: http://localhost:8080/auth/realms/mboss-realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: mboss-client
            client-secret: d3746ce4-4194-4c36-aca1-b2857e71faf1
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/demo/**
          filters:
            - RemoveRequestHeader=Cookie
      default-filters:
      - TokenRelay
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
    register-with-eureka: true
    fetch-registry: true
