server:
  port: 8765

logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
      security: DEBUG
      oauth2: DEBUG

keycloak:
  auth-server-url: http://localhost:8090/auth
  realm: mboss-realm-dev

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${keycloak.realm}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/keycloak
            scope: openid
        provider:
          keycloak:
            authorization-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            user-name-attribute: name
            user-info-authentication-method: header
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
      default-filters:
        - TokenRelay
#       globalcors:
#         corsConfigurations:
#           '[/**]':
#             allowedOrigins: "*"
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
#               - PATCH
#               - OPTIONS
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${CONFIG_SERVER_USERNAME}:${CONFIG_SERVER_PASSWORD}@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
