server:
  port: 8765

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-ms
          uri: lb://product-ms
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${server:port}
