server:
  port: 8765

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: product-ms
          uri: lb://product-ms
          predicates:
            - Path=/api/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/auth/realms/realm-ms
        registration:
          spring-cloud-gateway-client:
            client-id: client-ms
            client-secret: 90e00007-8faf-4309-a270-6f682e266134
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8765/login/oauth2/code/client-ms

eureka:
  instance:
    instance-id: ${spring.application.name}:${server:port}
