server:
  port: 42550

spring:
  application:
    name: product-ms
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  h2:
    console:
      enable: true
      path: /h2-console
  cloud:
    config:
      import-check:
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${server:port}
